name: Lint
on:
  pull_request:
  push:
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: python3 -m pip install poetry==2.0.1 && make init

      - name: Run all linters and formatters
        run: make lint