name: Tests and Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: python3 -m pip install poetry==2.0.1 && make init

      - name: Run tests
        run: make test